// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "DriveTrain.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    leftFront = RobotMap::driveTrainLeftFront;
    leftRear = RobotMap::driveTrainLeftRear;
    rightFront = RobotMap::driveTrainRightFront;
    rightRear = RobotMap::driveTrainRightRear;
    robotDrive41 = RobotMap::driveTrainRobotDrive41;
    comp = RobotMap::driveTrainComp;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    drive_x = 0;
    drive_y = 0;
}

void DriveTrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void DriveTrain::JoyDrive(std::shared_ptr<Joystick> joy)
{
	drive_x = joy->GetX() /* * .75*/;
	drive_y = joy->GetY() /* * .75*/;
	leftFront->Set(pow(drive_x, 3) + pow(-drive_y, 3));
	leftRear->Set(pow(drive_x, 3) + pow(-drive_y, 3));
	rightFront->Set(pow(drive_x, 3) + pow(drive_y, 3));
	rightRear->Set(pow(drive_x, 3) + pow(drive_y, 3));
}
